info:
  app:
    name: config-service
    description: config Service Microservice
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers, metrics, prometheus, env, beans, configprops, threaddump
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

spring:
  application:
    name: discovery-service

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: INFO         
    org.loop.troop: INFO  
    org.springframework.web: ERROR  

