spring:
  profiles:
    active: dev
  application:
    name: discovery-service
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    root: INFO         
    org.loop.troop: INFO  
    org.springframework.web: ERROR  

management:
  endpoints:
    web:
      exposure:
        include: loggers

