info:
  app:
    name: config-service
    description: config Service Microservice
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers, metrics, prometheus, env, beans, configprops, threaddump
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

server:
  port: 4002

eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_CLIENT_URL:http://localhost:8761/eureka/}

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          label: main
          uri: https://github.com/vivekPandeyDev/config
          clone-on-start: true